INSERT INTO `ordersDetails` 
(`id`,
    `order`,
    `manufactureDate`,
    `sellDate`,
    `expiryDate`,
    `daysToExpiry`,
    `codebar`,
    `UM`,
    `productCode`,
    `batch`,
    `packages`,
    `noSell`,
    `Quantity`,
    `QuantityReal`,
    `UnitPrice`,
    `Subtotal`,
    `taxes`,
    `Discount`,
    `LineTotal`,
    `section`,
    `transaction_type`,
    `skBatches`,
    `averagePrice`,
    `averageWeight`,
    `commission`,
    `return`,
    `supplierCode`)
SELECT
    `id`,
    {$recID} as `order`,
    `manufactureDate`,
    `sellDate`,
    `expiryDate`,
    `daysToExpiry`,
    `codebar`,
    `UM`,
    `productCode`,
    `batch`,
    `packages`,
    `noSell`,
    `Quantity`,
    `QuantityReal`,
    `UnitPrice`,
    `Subtotal`,
    `taxes`,
    `Discount`,
    `LineTotal`,
    `section`,
    `transaction_type`,
    `skBatches`,
    `averagePrice`,
    `averageWeight`,
    `commission`,
    `return`,
    `supplierCode`
FROM
    `SQL_ordersDetails`
WHERE company = {$company_id} 
AND customer ={$customer_id} 
AND MONTH = {$month_} 
AND YEAR = {$year_}