<?php

// Data functions (insert, update, delete, form) for table attributes

// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

function attributes_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('attributes');
	if(!$arrPerm[1]){
		return false;
	}

	$data['attribute'] = makeSafe($_REQUEST['attribute']);
		if($data['attribute'] == empty_lookup_value){ $data['attribute'] = ''; }
	$data['value'] = br2nl(makeSafe($_REQUEST['value']));
	$data['contact'] = makeSafe($_REQUEST['contact']);
		if($data['contact'] == empty_lookup_value){ $data['contact'] = ''; }
	$data['companies'] = makeSafe($_REQUEST['companies']);
		if($data['companies'] == empty_lookup_value){ $data['companies'] = ''; }
	$data['products'] = makeSafe($_REQUEST['products']);
		if($data['products'] == empty_lookup_value){ $data['products'] = ''; }

	// hook: attributes_before_insert
	if(function_exists('attributes_before_insert')){
		$args=array();
		if(!attributes_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `attributes` set       `attribute`=' . (($data['attribute'] !== '' && $data['attribute'] !== NULL) ? "'{$data['attribute']}'" : 'NULL') . ', `value`=' . (($data['value'] !== '' && $data['value'] !== NULL) ? "'{$data['value']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"attributes_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// automatic contact
	if($_REQUEST['filterer_contact']){
		sql("update `attributes` set `contact`='" . makeSafe($_REQUEST['filterer_contact']) . "' where `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	// automatic companies
	if($_REQUEST['filterer_companies']){
		sql("update `attributes` set `companies`='" . makeSafe($_REQUEST['filterer_companies']) . "' where `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	// automatic products
	if($_REQUEST['filterer_products']){
		sql("update `attributes` set `products`='" . makeSafe($_REQUEST['filterer_products']) . "' where `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: attributes_after_insert
	if(function_exists('attributes_after_insert')){
		$res = sql("select * from `attributes` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!attributes_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('attributes', $recID, getLoggedMemberID());

	return $recID;
}

function attributes_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('attributes');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='attributes' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='attributes' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: attributes_before_delete
	if(function_exists('attributes_before_delete')){
		$args=array();
		if(!attributes_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `attributes` where `id`='$selected_id'", $eo);

	// hook: attributes_after_delete
	if(function_exists('attributes_after_delete')){
		$args=array();
		attributes_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='attributes' and pkValue='$selected_id'", $eo);
}

function attributes_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('attributes');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='attributes' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='attributes' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['attribute'] = makeSafe($_REQUEST['attribute']);
		if($data['attribute'] == empty_lookup_value){ $data['attribute'] = ''; }
	$data['value'] = br2nl(makeSafe($_REQUEST['value']));
	$data['contact'] = makeSafe($_REQUEST['contact']);
		if($data['contact'] == empty_lookup_value){ $data['contact'] = ''; }
	$data['companies'] = makeSafe($_REQUEST['companies']);
		if($data['companies'] == empty_lookup_value){ $data['companies'] = ''; }
	$data['products'] = makeSafe($_REQUEST['products']);
		if($data['products'] == empty_lookup_value){ $data['products'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: attributes_before_update
	if(function_exists('attributes_before_update')){
		$args=array();
		if(!attributes_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `attributes` set       `attribute`=' . (($data['attribute'] !== '' && $data['attribute'] !== NULL) ? "'{$data['attribute']}'" : 'NULL') . ', `value`=' . (($data['value'] !== '' && $data['value'] !== NULL) ? "'{$data['value']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="attributes_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: attributes_after_update
	if(function_exists('attributes_after_update')){
		$res = sql("SELECT * FROM `attributes` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!attributes_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='attributes' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function attributes_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('attributes');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_attribute = thisOr(undo_magic_quotes($_REQUEST['filterer_attribute']), '');
	$filterer_contact = thisOr(undo_magic_quotes($_REQUEST['filterer_contact']), '');
	$filterer_companies = thisOr(undo_magic_quotes($_REQUEST['filterer_companies']), '');
	$filterer_products = thisOr(undo_magic_quotes($_REQUEST['filterer_products']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: attribute
	$combo_attribute = new DataCombo;
	// combobox: contact
	$combo_contact = new DataCombo;
	// combobox: companies
	$combo_companies = new DataCombo;
	// combobox: products
	$combo_products = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='attributes' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='attributes' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `attributes` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'attributes_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_attribute->SelectedData = $row['attribute'];
		$combo_contact->SelectedData = $row['contact'];
		$combo_companies->SelectedData = $row['companies'];
		$combo_products->SelectedData = $row['products'];
	}else{
		$combo_attribute->SelectedData = $filterer_attribute;
		$combo_contact->SelectedData = $filterer_contact;
		$combo_companies->SelectedData = $filterer_companies;
		$combo_products->SelectedData = $filterer_products;
	}
	$combo_attribute->HTML = '<span id="attribute-container' . $rnd1 . '"></span><input type="hidden" name="attribute" id="attribute' . $rnd1 . '" value="' . html_attr($combo_attribute->SelectedData) . '">';
	$combo_attribute->MatchText = '<span id="attribute-container-readonly' . $rnd1 . '"></span><input type="hidden" name="attribute" id="attribute' . $rnd1 . '" value="' . html_attr($combo_attribute->SelectedData) . '">';
	$combo_contact->HTML = '<span id="contact-container' . $rnd1 . '"></span><input type="hidden" name="contact" id="contact' . $rnd1 . '" value="' . html_attr($combo_contact->SelectedData) . '">';
	$combo_contact->MatchText = '<span id="contact-container-readonly' . $rnd1 . '"></span><input type="hidden" name="contact" id="contact' . $rnd1 . '" value="' . html_attr($combo_contact->SelectedData) . '">';
	$combo_companies->HTML = '<span id="companies-container' . $rnd1 . '"></span><input type="hidden" name="companies" id="companies' . $rnd1 . '" value="' . html_attr($combo_companies->SelectedData) . '">';
	$combo_companies->MatchText = '<span id="companies-container-readonly' . $rnd1 . '"></span><input type="hidden" name="companies" id="companies' . $rnd1 . '" value="' . html_attr($combo_companies->SelectedData) . '">';
	$combo_products->HTML = '<span id="products-container' . $rnd1 . '"></span><input type="hidden" name="products" id="products' . $rnd1 . '" value="' . html_attr($combo_products->SelectedData) . '">';
	$combo_products->MatchText = '<span id="products-container-readonly' . $rnd1 . '"></span><input type="hidden" name="products" id="products' . $rnd1 . '" value="' . html_attr($combo_products->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_attribute__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['attribute'] : $filterer_attribute); ?>"};
		AppGini.current_contact__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['contact'] : $filterer_contact); ?>"};
		AppGini.current_companies__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['companies'] : $filterer_companies); ?>"};
		AppGini.current_products__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['products'] : $filterer_products); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(attribute_reload__RAND__) == 'function') attribute_reload__RAND__();
				if(typeof(contact_reload__RAND__) == 'function') contact_reload__RAND__();
				if(typeof(companies_reload__RAND__) == 'function') companies_reload__RAND__();
				if(typeof(products_reload__RAND__) == 'function') products_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function attribute_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#attribute-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_attribute__RAND__.value, t: 'attributes', f: 'attribute' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="attribute"]').val(resp.results[0].id);
							$j('[id=attribute-container-readonly__RAND__]').html('<span id="attribute-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=kinds_view_parent]').hide(); }else{ $j('.btn[id=kinds_view_parent]').show(); }


							if(typeof(attribute_update_autofills__RAND__) == 'function') attribute_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'attributes', f: 'attribute' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_attribute__RAND__.value = e.added.id;
				AppGini.current_attribute__RAND__.text = e.added.text;
				$j('[name="attribute"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=kinds_view_parent]').hide(); }else{ $j('.btn[id=kinds_view_parent]').show(); }


				if(typeof(attribute_update_autofills__RAND__) == 'function') attribute_update_autofills__RAND__();
			});

			if(!$j("#attribute-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_attribute__RAND__.value, t: 'attributes', f: 'attribute' },
					success: function(resp){
						$j('[name="attribute"]').val(resp.results[0].id);
						$j('[id=attribute-container-readonly__RAND__]').html('<span id="attribute-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=kinds_view_parent]').hide(); }else{ $j('.btn[id=kinds_view_parent]').show(); }

						if(typeof(attribute_update_autofills__RAND__) == 'function') attribute_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_attribute__RAND__.value, t: 'attributes', f: 'attribute' },
				success: function(resp){
					$j('[id=attribute-container__RAND__], [id=attribute-container-readonly__RAND__]').html('<span id="attribute-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=kinds_view_parent]').hide(); }else{ $j('.btn[id=kinds_view_parent]').show(); }

					if(typeof(attribute_update_autofills__RAND__) == 'function') attribute_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function contact_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#contact-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_contact__RAND__.value, t: 'attributes', f: 'contact' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="contact"]').val(resp.results[0].id);
							$j('[id=contact-container-readonly__RAND__]').html('<span id="contact-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').hide(); }else{ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').show(); }


							if(typeof(contact_update_autofills__RAND__) == 'function') contact_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'attributes', f: 'contact' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_contact__RAND__.value = e.added.id;
				AppGini.current_contact__RAND__.text = e.added.text;
				$j('[name="contact"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').hide(); }else{ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').show(); }


				if(typeof(contact_update_autofills__RAND__) == 'function') contact_update_autofills__RAND__();
			});

			if(!$j("#contact-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_contact__RAND__.value, t: 'attributes', f: 'contact' },
					success: function(resp){
						$j('[name="contact"]').val(resp.results[0].id);
						$j('[id=contact-container-readonly__RAND__]').html('<span id="contact-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').hide(); }else{ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').show(); }

						if(typeof(contact_update_autofills__RAND__) == 'function') contact_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_contact__RAND__.value, t: 'attributes', f: 'contact' },
				success: function(resp){
					$j('[id=contact-container__RAND__], [id=contact-container-readonly__RAND__]').html('<span id="contact-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').hide(); }else{ $j('.btn[id=CLIENTI_CESSIONARI_PA_view_parent]').show(); }

					if(typeof(contact_update_autofills__RAND__) == 'function') contact_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function companies_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#companies-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_companies__RAND__.value, t: 'attributes', f: 'companies' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="companies"]').val(resp.results[0].id);
							$j('[id=companies-container-readonly__RAND__]').html('<span id="companies-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=companies_view_parent]').hide(); }else{ $j('.btn[id=companies_view_parent]').show(); }


							if(typeof(companies_update_autofills__RAND__) == 'function') companies_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'attributes', f: 'companies' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_companies__RAND__.value = e.added.id;
				AppGini.current_companies__RAND__.text = e.added.text;
				$j('[name="companies"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=companies_view_parent]').hide(); }else{ $j('.btn[id=companies_view_parent]').show(); }


				if(typeof(companies_update_autofills__RAND__) == 'function') companies_update_autofills__RAND__();
			});

			if(!$j("#companies-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_companies__RAND__.value, t: 'attributes', f: 'companies' },
					success: function(resp){
						$j('[name="companies"]').val(resp.results[0].id);
						$j('[id=companies-container-readonly__RAND__]').html('<span id="companies-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=companies_view_parent]').hide(); }else{ $j('.btn[id=companies_view_parent]').show(); }

						if(typeof(companies_update_autofills__RAND__) == 'function') companies_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_companies__RAND__.value, t: 'attributes', f: 'companies' },
				success: function(resp){
					$j('[id=companies-container__RAND__], [id=companies-container-readonly__RAND__]').html('<span id="companies-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=companies_view_parent]').hide(); }else{ $j('.btn[id=companies_view_parent]').show(); }

					if(typeof(companies_update_autofills__RAND__) == 'function') companies_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function products_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#products-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_products__RAND__.value, t: 'attributes', f: 'products' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="products"]').val(resp.results[0].id);
							$j('[id=products-container-readonly__RAND__]').html('<span id="products-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=products_view_parent]').hide(); }else{ $j('.btn[id=products_view_parent]').show(); }


							if(typeof(products_update_autofills__RAND__) == 'function') products_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'attributes', f: 'products' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_products__RAND__.value = e.added.id;
				AppGini.current_products__RAND__.text = e.added.text;
				$j('[name="products"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=products_view_parent]').hide(); }else{ $j('.btn[id=products_view_parent]').show(); }


				if(typeof(products_update_autofills__RAND__) == 'function') products_update_autofills__RAND__();
			});

			if(!$j("#products-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_products__RAND__.value, t: 'attributes', f: 'products' },
					success: function(resp){
						$j('[name="products"]').val(resp.results[0].id);
						$j('[id=products-container-readonly__RAND__]').html('<span id="products-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=products_view_parent]').hide(); }else{ $j('.btn[id=products_view_parent]').show(); }

						if(typeof(products_update_autofills__RAND__) == 'function') products_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_products__RAND__.value, t: 'attributes', f: 'products' },
				success: function(resp){
					$j('[id=products-container__RAND__], [id=products-container-readonly__RAND__]').html('<span id="products-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=products_view_parent]').hide(); }else{ $j('.btn[id=products_view_parent]').show(); }

					if(typeof(products_update_autofills__RAND__) == 'function') products_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/attributes_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/attributes_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Attribute details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return attributes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return attributes_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return attributes_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#attribute').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#attribute_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#value').replaceWith('<div class=\"form-control-static\" id=\"value\">' + (jQuery('#value').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(attribute)%%>', $combo_attribute->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(attribute)%%>', $combo_attribute->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(attribute)%%>', urlencode($combo_attribute->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(contact)%%>', $combo_contact->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(contact)%%>', $combo_contact->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(contact)%%>', urlencode($combo_contact->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(companies)%%>', $combo_companies->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(companies)%%>', $combo_companies->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(companies)%%>', urlencode($combo_companies->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(products)%%>', $combo_products->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(products)%%>', $combo_products->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(products)%%>', urlencode($combo_products->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'attribute' => array('kinds', 'Attribute'), 'contact' => array('CLIENTI_CESSIONARI_PA', 'Contact'), 'companies' => array('companies', 'Companies'), 'products' => array('products', 'Products'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(attribute)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(value)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(contact)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(companies)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(products)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(attribute)%%>', safe_html($urow['attribute']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(attribute)%%>', html_attr($row['attribute']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(attribute)%%>', urlencode($urow['attribute']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)){
			$templateCode = str_replace('<%%VALUE(value)%%>', safe_html($urow['value']), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(value)%%>', html_attr($row['value']), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(value)%%>', urlencode($urow['value']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(contact)%%>', safe_html($urow['contact']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(contact)%%>', html_attr($row['contact']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact)%%>', urlencode($urow['contact']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(companies)%%>', safe_html($urow['companies']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(companies)%%>', html_attr($row['companies']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(companies)%%>', urlencode($urow['companies']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(products)%%>', safe_html($urow['products']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(products)%%>', html_attr($row['products']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(products)%%>', urlencode($urow['products']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(attribute)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(attribute)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(value)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(value)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(contact)%%>', ( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_contact->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(contact)%%>', urlencode( $_REQUEST['FilterField'][1]=='4' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_contact->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%VALUE(companies)%%>', ( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_companies->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(companies)%%>', urlencode( $_REQUEST['FilterField'][1]=='5' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_companies->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%VALUE(products)%%>', ( $_REQUEST['FilterField'][1]=='6' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_products->SelectedData : ''), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(products)%%>', urlencode( $_REQUEST['FilterField'][1]=='6' && $_REQUEST['FilterOperator'][1]=='<=>' ? $combo_products->SelectedData : ''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('attributes');
	if($selected_id){
		$jdata = get_joined_record('attributes', $selected_id);
		if($jdata === false) $jdata = get_defaults('attributes');
		$rdata = $row;
	}
	$templateCode .= loadView('attributes-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: attributes_dv
	if(function_exists('attributes_dv')){
		$args=array();
		attributes_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>