<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/CLIENTI_CESSIONARI_PA.php");
	include("$currDir/CLIENTI_CESSIONARI_PA_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('CLIENTI_CESSIONARI_PA');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "CLIENTI_CESSIONARI_PA";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`CLIENTI_CESSIONARI_PA`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* IdPaese_Cessionario PA */" => "idPaese_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`idCodice_Ces_PA`" => "idCodice_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`codiceFiscale_Ces_PA`" => "codiceFiscale_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`Denominazione_Ces_PA`" => "Denominazione_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`tit_Ces_PA`" => "tit_Ces_PA",
		"if(CHAR_LENGTH(`CLIENTI_CESSIONARI_PA`.`nome_Ces_PA`)>100, concat(left(`CLIENTI_CESSIONARI_PA`.`nome_Ces_PA`,100),' ...'), `CLIENTI_CESSIONARI_PA`.`nome_Ces_PA`)" => "nome_Ces_PA",
		"if(CHAR_LENGTH(`CLIENTI_CESSIONARI_PA`.`cogn_Ces_PA`)>100, concat(left(`CLIENTI_CESSIONARI_PA`.`cogn_Ces_PA`,100),' ...'), `CLIENTI_CESSIONARI_PA`.`cogn_Ces_PA`)" => "cogn_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`Cod_Ces_EORI_PA`" => "Cod_Ces_EORI_PA",
		"`CLIENTI_CESSIONARI_PA`.`indirizzo_Ces_PA`" => "indirizzo_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`numeroCiv_CesPA`" => "numeroCiv_CesPA",
		"`CLIENTI_CESSIONARI_PA`.`CAP_Ces_PA`" => "CAP_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`comune_Ces_PA`" => "comune_Ces_PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* Provincia Ces. PA */" => "pr_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`nazione_Ces_PA`" => "nazione_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`notes`" => "notes",
		"if(`CLIENTI_CESSIONARI_PA`.`birthDate`,date_format(`CLIENTI_CESSIONARI_PA`.`birthDate`,'%Y-%m-%d'),'')" => "birthDate",
		"`CLIENTI_CESSIONARI_PA`.`autorizzSanitaria_SAM`" => "autorizzSanitaria_SAM",
		"`CLIENTI_CESSIONARI_PA`.`AutSanEmessa_SAM`" => "AutSanEmessa_SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrPresSan_SAM`" => "NrPresSan_SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrAutSan_SAM`" => "NrAutSan_SAM",
		"if(`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`,date_format(`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`,'%Y-%m-%d'),'')" => "dataAutSan_SAM"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`CLIENTI_CESSIONARI_PA`.`id`',
		2 => '`kinds1`.`name`',
		3 => '`countries1`.`code`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => '`town1`.`district`',
		16 => 16,
		17 => 17,
		18 => '`CLIENTI_CESSIONARI_PA`.`birthDate`',
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => '`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`CLIENTI_CESSIONARI_PA`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* IdPaese_Cessionario PA */" => "idPaese_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`idCodice_Ces_PA`" => "idCodice_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`codiceFiscale_Ces_PA`" => "codiceFiscale_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`Denominazione_Ces_PA`" => "Denominazione_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`tit_Ces_PA`" => "tit_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`nome_Ces_PA`" => "nome_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`cogn_Ces_PA`" => "cogn_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`Cod_Ces_EORI_PA`" => "Cod_Ces_EORI_PA",
		"`CLIENTI_CESSIONARI_PA`.`indirizzo_Ces_PA`" => "indirizzo_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`numeroCiv_CesPA`" => "numeroCiv_CesPA",
		"`CLIENTI_CESSIONARI_PA`.`CAP_Ces_PA`" => "CAP_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`comune_Ces_PA`" => "comune_Ces_PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* Provincia Ces. PA */" => "pr_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`nazione_Ces_PA`" => "nazione_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`notes`" => "notes",
		"if(`CLIENTI_CESSIONARI_PA`.`birthDate`,date_format(`CLIENTI_CESSIONARI_PA`.`birthDate`,'%Y-%m-%d'),'')" => "birthDate",
		"`CLIENTI_CESSIONARI_PA`.`autorizzSanitaria_SAM`" => "autorizzSanitaria_SAM",
		"`CLIENTI_CESSIONARI_PA`.`AutSanEmessa_SAM`" => "AutSanEmessa_SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrPresSan_SAM`" => "NrPresSan_SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrAutSan_SAM`" => "NrAutSan_SAM",
		"if(`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`,date_format(`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`,'%Y-%m-%d'),'')" => "dataAutSan_SAM"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`CLIENTI_CESSIONARI_PA`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "Kind",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* IdPaese_Cessionario PA */" => "IdPaese_Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`idCodice_Ces_PA`" => "IdCodice Ces PA",
		"`CLIENTI_CESSIONARI_PA`.`codiceFiscale_Ces_PA`" => "CodiceFiscale Ces PA",
		"`CLIENTI_CESSIONARI_PA`.`Denominazione_Ces_PA`" => "Denominazione Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`tit_Ces_PA`" => "Titolo Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`nome_Ces_PA`" => "Nome Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`cogn_Ces_PA`" => "Cognome Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`Cod_Ces_EORI_PA`" => "Codice EORI Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`indirizzo_Ces_PA`" => "Indirizzo Ces. PA",
		"`CLIENTI_CESSIONARI_PA`.`numeroCiv_CesPA`" => "Numero Civico Ces. PA",
		"`CLIENTI_CESSIONARI_PA`.`CAP_Ces_PA`" => "CAP Ces. PA",
		"`CLIENTI_CESSIONARI_PA`.`comune_Ces_PA`" => "Comune Ces. PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* Provincia Ces. PA */" => "Provincia Ces. PA",
		"`CLIENTI_CESSIONARI_PA`.`nazione_Ces_PA`" => "Nazione Ces. PA",
		"`CLIENTI_CESSIONARI_PA`.`notes`" => "Notes",
		"`CLIENTI_CESSIONARI_PA`.`birthDate`" => "Birth Date",
		"`CLIENTI_CESSIONARI_PA`.`autorizzSanitaria_SAM`" => "Autorizzazione Sanitaria SAM",
		"`CLIENTI_CESSIONARI_PA`.`AutSanEmessa_SAM`" => "AutSanEmessa SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrPresSan_SAM`" => "NrPresSan SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrAutSan_SAM`" => "NrAutSan SAM",
		"`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`" => "DataAutSan SAM"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`CLIENTI_CESSIONARI_PA`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* IdPaese_Cessionario PA */" => "idPaese_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`idCodice_Ces_PA`" => "idCodice_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`codiceFiscale_Ces_PA`" => "codiceFiscale_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`Denominazione_Ces_PA`" => "Denominazione_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`tit_Ces_PA`" => "Titolo Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`nome_Ces_PA`" => "Nome Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`cogn_Ces_PA`" => "Cognome Cessionario PA",
		"`CLIENTI_CESSIONARI_PA`.`Cod_Ces_EORI_PA`" => "Cod_Ces_EORI_PA",
		"`CLIENTI_CESSIONARI_PA`.`indirizzo_Ces_PA`" => "indirizzo_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`numeroCiv_CesPA`" => "numeroCiv_CesPA",
		"`CLIENTI_CESSIONARI_PA`.`CAP_Ces_PA`" => "CAP_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`comune_Ces_PA`" => "comune_Ces_PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* Provincia Ces. PA */" => "pr_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`nazione_Ces_PA`" => "nazione_Ces_PA",
		"`CLIENTI_CESSIONARI_PA`.`notes`" => "notes",
		"if(`CLIENTI_CESSIONARI_PA`.`birthDate`,date_format(`CLIENTI_CESSIONARI_PA`.`birthDate`,'%Y-%m-%d'),'')" => "birthDate",
		"`CLIENTI_CESSIONARI_PA`.`autorizzSanitaria_SAM`" => "autorizzSanitaria_SAM",
		"`CLIENTI_CESSIONARI_PA`.`AutSanEmessa_SAM`" => "AutSanEmessa_SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrPresSan_SAM`" => "NrPresSan_SAM",
		"`CLIENTI_CESSIONARI_PA`.`NrAutSan_SAM`" => "NrAutSan_SAM",
		"if(`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`,date_format(`CLIENTI_CESSIONARI_PA`.`dataAutSan_SAM`,'%Y-%m-%d'),'')" => "dataAutSan_SAM"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'kind' => 'Kind', 'idPaese_Ces_PA' => 'IdPaese_Cessionario PA', 'pr_Ces_PA' => 'Provincia Ces. PA');

	$x->QueryFrom = "`CLIENTI_CESSIONARI_PA` LEFT JOIN `kinds` as kinds1 ON `kinds1`.`code`=`CLIENTI_CESSIONARI_PA`.`kind` LEFT JOIN `countries` as countries1 ON `countries1`.`id`=`CLIENTI_CESSIONARI_PA`.`idPaese_Ces_PA` LEFT JOIN `town` as town1 ON `town1`.`id`=`CLIENTI_CESSIONARI_PA`.`pr_Ces_PA` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "CLIENTI_CESSIONARI_PA_view.php";
	$x->RedirectAfterInsert = "CLIENTI_CESSIONARI_PA_view.php?SelectedID=#ID#";
	$x->TableTitle = "Cessionario Committente PA";
	$x->TableIcon = "resources/table_icons/client_account_template.png";
	$x->PrimaryKey = "`CLIENTI_CESSIONARI_PA`.`id`";
	$x->DefaultSortField = '9';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Kind", "IdPaese_Cessionario PA", "IdCodice Ces PA", "CodiceFiscale Ces PA", "Denominazione Cessionario PA", "Titolo Cessionario PA", "Nome Cessionario PA", "Cognome Cessionario PA", "Indirizzo Ces. PA", "Numero Civico Ces. PA", "CAP Ces. PA", "Comune Ces. PA", "Provincia Ces. PA", "Nazione Ces. PA", "Notes", "Birth Date", "Autorizzazione Sanitaria SAM", "AutSanEmessa SAM", "NrPresSan SAM", "NrAutSan SAM", "DataAutSan SAM");
	$x->ColFieldName = array('kind', 'idPaese_Ces_PA', 'idCodice_Ces_PA', 'codiceFiscale_Ces_PA', 'Denominazione_Ces_PA', 'tit_Ces_PA', 'nome_Ces_PA', 'cogn_Ces_PA', 'indirizzo_Ces_PA', 'numeroCiv_CesPA', 'CAP_Ces_PA', 'comune_Ces_PA', 'pr_Ces_PA', 'nazione_Ces_PA', 'notes', 'birthDate', 'autorizzSanitaria_SAM', 'AutSanEmessa_SAM', 'NrPresSan_SAM', 'NrAutSan_SAM', 'dataAutSan_SAM');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23);

	// template paths below are based on the app main directory
	$x->Template = 'templates/CLIENTI_CESSIONARI_PA_templateTV.html';
	$x->SelectedTemplate = 'templates/CLIENTI_CESSIONARI_PA_templateTVS.html';
	$x->TemplateDV = 'templates/CLIENTI_CESSIONARI_PA_templateDV.html';
	$x->TemplateDVP = 'templates/CLIENTI_CESSIONARI_PA_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `CLIENTI_CESSIONARI_PA`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='CLIENTI_CESSIONARI_PA' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `CLIENTI_CESSIONARI_PA`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='CLIENTI_CESSIONARI_PA' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`CLIENTI_CESSIONARI_PA`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: CLIENTI_CESSIONARI_PA_init
	$render=TRUE;
	if(function_exists('CLIENTI_CESSIONARI_PA_init')){
		$args=array();
		$render=CLIENTI_CESSIONARI_PA_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: CLIENTI_CESSIONARI_PA_header
	$headerCode='';
	if(function_exists('CLIENTI_CESSIONARI_PA_header')){
		$args=array();
		$headerCode=CLIENTI_CESSIONARI_PA_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: CLIENTI_CESSIONARI_PA_footer
	$footerCode='';
	if(function_exists('CLIENTI_CESSIONARI_PA_footer')){
		$args=array();
		$footerCode=CLIENTI_CESSIONARI_PA_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>