<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/companies.php");
	include("$currDir/companies_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('companies');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "companies";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`companies`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"if(CHAR_LENGTH(`companies`.`companyCode`)>100, concat(left(`companies`.`companyCode`,100),' ...'), `companies`.`companyCode`)" => "companyCode",
		"if(CHAR_LENGTH(`companies`.`companyName`)>100, concat(left(`companies`.`companyName`,100),' ...'), `companies`.`companyName`)" => "companyName",
		"`companies`.`notes`" => "notes",
		"`companies`.`codiceDestinatarioUff_PA`" => "codiceDestinatarioUff_PA",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Id Paese  */" => "idPaese_Ced_PA",
		"`companies`.`idCodice_Ced_PA`" => "idCodice_Ced_PA",
		"`companies`.`codiceFiscale_Ced_PA`" => "codiceFiscale_Ced_PA",
		"`companies`.`denominazione_Ced_PA`" => "denominazione_Ced_PA",
		"`companies`.`titolo_Ced_PA`" => "titolo_Ced_PA",
		"`companies`.`nome_Ced_PA`" => "nome_Ced_PA",
		"`companies`.`cognome_Ced_PA`" => "cognome_Ced_PA",
		"`companies`.`codEORICed__PA`" => "codEORICed__PA",
		"`companies`.`alboProfessionale_Ced_PA`" => "alboProfessionale_Ced_PA",
		"`companies`.`provinciaAlbo_Ced_PA`" => "provinciaAlbo_Ced_PA",
		"`companies`.`numeroIscrizione_Ced_AlboPA`" => "numeroIscrizione_Ced_AlboPA",
		"if(`companies`.`dataIscrAlbo_Ced_PA`,date_format(`companies`.`dataIscrAlbo_Ced_PA`,'%Y-%m-%d'),'')" => "dataIscrAlbo_Ced_PA",
		"`companies`.`regimeFiscalePA`" => "regimeFiscalePA",
		"`companies`.`idPaeseVett_PA`" => "idPaeseVett_PA",
		"`companies`.`idFiscaleVet_PA`" => "idFiscaleVet_PA",
		"`companies`.`codFiscVet_PA`" => "codFiscVet_PA",
		"`companies`.`denominazioneVet_PA`" => "denominazioneVet_PA",
		"`companies`.`titoloVet_PA`" => "titoloVet_PA",
		"`companies`.`nomeVet_PA`" => "nomeVet_PA",
		"`companies`.`cognomeVett_PA`" => "cognomeVett_PA",
		"`companies`.`codEORIVet_PA`" => "codEORIVet_PA",
		"`companies`.`nrLicGuidaVet_PA`" => "nrLicGuidaVet_PA",
		"if(`companies`.`data_DatiVeic_PA`,date_format(`companies`.`data_DatiVeic_PA`,'%Y-%m-%d'),'')" => "data_DatiVeic_PA",
		"`companies`.`totalPercVeic_PA`" => "totalPercVeic_PA",
		"`companies`.`mezzoTrVet_PA`" => "mezzoTrVet_PA"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`companies`.`id`',
		2 => '`kinds1`.`name`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`companies`.`codiceDestinatarioUff_PA`',
		7 => '`countries1`.`country`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => '`companies`.`dataIscrAlbo_Ced_PA`',
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => 28,
		29 => '`companies`.`data_DatiVeic_PA`',
		30 => 30,
		31 => 31
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`companies`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"`companies`.`companyCode`" => "companyCode",
		"`companies`.`companyName`" => "companyName",
		"`companies`.`notes`" => "notes",
		"`companies`.`codiceDestinatarioUff_PA`" => "codiceDestinatarioUff_PA",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Id Paese  */" => "idPaese_Ced_PA",
		"`companies`.`idCodice_Ced_PA`" => "idCodice_Ced_PA",
		"`companies`.`codiceFiscale_Ced_PA`" => "codiceFiscale_Ced_PA",
		"`companies`.`denominazione_Ced_PA`" => "denominazione_Ced_PA",
		"`companies`.`titolo_Ced_PA`" => "titolo_Ced_PA",
		"`companies`.`nome_Ced_PA`" => "nome_Ced_PA",
		"`companies`.`cognome_Ced_PA`" => "cognome_Ced_PA",
		"`companies`.`codEORICed__PA`" => "codEORICed__PA",
		"`companies`.`alboProfessionale_Ced_PA`" => "alboProfessionale_Ced_PA",
		"`companies`.`provinciaAlbo_Ced_PA`" => "provinciaAlbo_Ced_PA",
		"`companies`.`numeroIscrizione_Ced_AlboPA`" => "numeroIscrizione_Ced_AlboPA",
		"if(`companies`.`dataIscrAlbo_Ced_PA`,date_format(`companies`.`dataIscrAlbo_Ced_PA`,'%Y-%m-%d'),'')" => "dataIscrAlbo_Ced_PA",
		"`companies`.`regimeFiscalePA`" => "regimeFiscalePA",
		"`companies`.`idPaeseVett_PA`" => "idPaeseVett_PA",
		"`companies`.`idFiscaleVet_PA`" => "idFiscaleVet_PA",
		"`companies`.`codFiscVet_PA`" => "codFiscVet_PA",
		"`companies`.`denominazioneVet_PA`" => "denominazioneVet_PA",
		"`companies`.`titoloVet_PA`" => "titoloVet_PA",
		"`companies`.`nomeVet_PA`" => "nomeVet_PA",
		"`companies`.`cognomeVett_PA`" => "cognomeVett_PA",
		"`companies`.`codEORIVet_PA`" => "codEORIVet_PA",
		"`companies`.`nrLicGuidaVet_PA`" => "nrLicGuidaVet_PA",
		"if(`companies`.`data_DatiVeic_PA`,date_format(`companies`.`data_DatiVeic_PA`,'%Y-%m-%d'),'')" => "data_DatiVeic_PA",
		"`companies`.`totalPercVeic_PA`" => "totalPercVeic_PA",
		"`companies`.`mezzoTrVet_PA`" => "mezzoTrVet_PA"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`companies`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "Kind",
		"`companies`.`companyCode`" => "CompanyCode",
		"`companies`.`companyName`" => "CompanyName",
		"`companies`.`notes`" => "Notes",
		"`companies`.`codiceDestinatarioUff_PA`" => "Codice Ufficio Pubbl.Amm.",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Id Paese  */" => "Id Paese ",
		"`companies`.`idCodice_Ced_PA`" => "Id Codice/P.IVA",
		"`companies`.`codiceFiscale_Ced_PA`" => "Codice Fiscale PA",
		"`companies`.`denominazione_Ced_PA`" => "Denominazione Ced PA",
		"`companies`.`titolo_Ced_PA`" => "Titolo Ced. PA",
		"`companies`.`nome_Ced_PA`" => "Nome cedente PA",
		"`companies`.`cognome_Ced_PA`" => "Cognome Cedente PA",
		"`companies`.`codEORICed__PA`" => "CodEORI Ced. PA",
		"`companies`.`alboProfessionale_Ced_PA`" => "Albo Professionale Ced. PA",
		"`companies`.`provinciaAlbo_Ced_PA`" => "Provincia Albo PA",
		"`companies`.`numeroIscrizione_Ced_AlboPA`" => "Numero IscrizioneAlbo PA",
		"`companies`.`dataIscrAlbo_Ced_PA`" => "Data Iscr. Albo PA",
		"`companies`.`regimeFiscalePA`" => "Regime Ced. Fiscale PA",
		"`companies`.`idPaeseVett_PA`" => "IdPaeseVett PA",
		"`companies`.`idFiscaleVet_PA`" => "IdFiscaleVettore PA",
		"`companies`.`codFiscVet_PA`" => "CodFiscVet PA",
		"`companies`.`denominazioneVet_PA`" => "DenominazioneVet PA",
		"`companies`.`titoloVet_PA`" => "TitoloVet PA",
		"`companies`.`nomeVet_PA`" => "NomeVet PA",
		"`companies`.`cognomeVett_PA`" => "CognomeVett PA",
		"`companies`.`codEORIVet_PA`" => "CodEORIVet PA",
		"`companies`.`nrLicGuidaVet_PA`" => "NrLicGuida Vettore PA",
		"`companies`.`data_DatiVeic_PA`" => "Data Dati Veic PA",
		"`companies`.`totalPercVeic_PA`" => "TotalPercVeic PA",
		"`companies`.`mezzoTrVet_PA`" => "MezzoTrVet PA"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`companies`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"`companies`.`companyCode`" => "CompanyCode",
		"`companies`.`companyName`" => "CompanyName",
		"`companies`.`notes`" => "notes",
		"`companies`.`codiceDestinatarioUff_PA`" => "codiceDestinatarioUff_PA",
		"IF(    CHAR_LENGTH(`countries1`.`country`), CONCAT_WS('',   `countries1`.`country`), '') /* Id Paese  */" => "idPaese_Ced_PA",
		"`companies`.`idCodice_Ced_PA`" => "Id Codice/P.IVA",
		"`companies`.`codiceFiscale_Ced_PA`" => "Codice Fiscale PA",
		"`companies`.`denominazione_Ced_PA`" => "denominazione_Ced_PA",
		"`companies`.`titolo_Ced_PA`" => "titolo_Ced_PA",
		"`companies`.`nome_Ced_PA`" => "nome_Ced_PA",
		"`companies`.`cognome_Ced_PA`" => "cognome_Ced_PA",
		"`companies`.`codEORICed__PA`" => "codEORICed__PA",
		"`companies`.`alboProfessionale_Ced_PA`" => "alboProfessionale_Ced_PA",
		"`companies`.`provinciaAlbo_Ced_PA`" => "provinciaAlbo_Ced_PA",
		"`companies`.`numeroIscrizione_Ced_AlboPA`" => "numeroIscrizione_Ced_AlboPA",
		"if(`companies`.`dataIscrAlbo_Ced_PA`,date_format(`companies`.`dataIscrAlbo_Ced_PA`,'%Y-%m-%d'),'')" => "dataIscrAlbo_Ced_PA",
		"`companies`.`regimeFiscalePA`" => "regimeFiscalePA",
		"`companies`.`idPaeseVett_PA`" => "idPaeseVett_PA",
		"`companies`.`idFiscaleVet_PA`" => "idFiscaleVet_PA",
		"`companies`.`codFiscVet_PA`" => "codFiscVet_PA",
		"`companies`.`denominazioneVet_PA`" => "denominazioneVet_PA",
		"`companies`.`titoloVet_PA`" => "titoloVet_PA",
		"`companies`.`nomeVet_PA`" => "nomeVet_PA",
		"`companies`.`cognomeVett_PA`" => "cognomeVett_PA",
		"`companies`.`codEORIVet_PA`" => "codEORIVet_PA",
		"`companies`.`nrLicGuidaVet_PA`" => "nrLicGuidaVet_PA",
		"if(`companies`.`data_DatiVeic_PA`,date_format(`companies`.`data_DatiVeic_PA`,'%Y-%m-%d'),'')" => "data_DatiVeic_PA",
		"`companies`.`totalPercVeic_PA`" => "totalPercVeic_PA",
		"`companies`.`mezzoTrVet_PA`" => "mezzoTrVet_PA"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'kind' => 'Kind', 'idPaese_Ced_PA' => 'Id Paese ');

	$x->QueryFrom = "`companies` LEFT JOIN `kinds` as kinds1 ON `kinds1`.`code`=`companies`.`kind` LEFT JOIN `countries` as countries1 ON `countries1`.`id`=`companies`.`idPaese_Ced_PA` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "companies_view.php";
	$x->RedirectAfterInsert = "companies_view.php?SelectedID=#ID#";
	$x->TableTitle = "Cedente Prestatore";
	$x->TableIcon = "resources/table_icons/factory.png";
	$x->PrimaryKey = "`companies`.`id`";
	$x->DefaultSortField = '4';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Kind", "CompanyCode", "CompanyName", "Notes", "Id Paese ", "Id Codice/P.IVA", "Codice Fiscale PA", "Denominazione Ced PA", "Titolo Ced. PA", "Nome cedente PA", "Cognome Cedente PA", "Regime Ced. Fiscale PA", "IdPaeseVett PA", "IdFiscaleVettore PA", "CodFiscVet PA", "DenominazioneVet PA", "TitoloVet PA", "NomeVet PA", "CognomeVett PA", "Data Dati Veic PA", "MezzoTrVet PA");
	$x->ColFieldName = array('kind', 'companyCode', 'companyName', 'notes', 'idPaese_Ced_PA', 'idCodice_Ced_PA', 'codiceFiscale_Ced_PA', 'denominazione_Ced_PA', 'titolo_Ced_PA', 'nome_Ced_PA', 'cognome_Ced_PA', 'regimeFiscalePA', 'idPaeseVett_PA', 'idFiscaleVet_PA', 'codFiscVet_PA', 'denominazioneVet_PA', 'titoloVet_PA', 'nomeVet_PA', 'cognomeVett_PA', 'data_DatiVeic_PA', 'mezzoTrVet_PA');
	$x->ColNumber  = array(2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 19, 20, 21, 22, 23, 24, 25, 26, 29, 31);

	// template paths below are based on the app main directory
	$x->Template = 'templates/companies_templateTV.html';
	$x->SelectedTemplate = 'templates/companies_templateTVS.html';
	$x->TemplateDV = 'templates/companies_templateDV.html';
	$x->TemplateDVP = 'templates/companies_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `companies`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='companies' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `companies`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='companies' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`companies`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: companies_init
	$render=TRUE;
	if(function_exists('companies_init')){
		$args=array();
		$render=companies_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: companies_header
	$headerCode='';
	if(function_exists('companies_header')){
		$args=array();
		$headerCode=companies_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: companies_footer
	$footerCode='';
	if(function_exists('companies_footer')){
		$args=array();
		$footerCode=companies_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>