<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/creditDocument.php");
	include("$currDir/creditDocument_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('creditDocument');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "creditDocument";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`creditDocument`.`id`" => "id",
		"if(CHAR_LENGTH(`creditDocument`.`incomingTypeDoc`)>100, concat(left(`creditDocument`.`incomingTypeDoc`,100),' ...'), `creditDocument`.`incomingTypeDoc`)" => "incomingTypeDoc",
		"if(CHAR_LENGTH(`creditDocument`.`customerID`)>100, concat(left(`creditDocument`.`customerID`,100),' ...'), `creditDocument`.`customerID`)" => "customerID",
		"if(CHAR_LENGTH(`creditDocument`.`nrDoc`)>100, concat(left(`creditDocument`.`nrDoc`,100),' ...'), `creditDocument`.`nrDoc`)" => "nrDoc",
		"if(`creditDocument`.`dateIncomingNote`,date_format(`creditDocument`.`dateIncomingNote`,'%Y-%m-%d'),'')" => "dateIncomingNote",
		"if(CHAR_LENGTH(`creditDocument`.`customerFirm`)>100, concat(left(`creditDocument`.`customerFirm`,100),' ...'), `creditDocument`.`customerFirm`)" => "customerFirm",
		"if(CHAR_LENGTH(`creditDocument`.`customerAddress`)>100, concat(left(`creditDocument`.`customerAddress`,100),' ...'), `creditDocument`.`customerAddress`)" => "customerAddress",
		"if(CHAR_LENGTH(`creditDocument`.`customerPostCode`)>100, concat(left(`creditDocument`.`customerPostCode`,100),' ...'), `creditDocument`.`customerPostCode`)" => "customerPostCode",
		"if(CHAR_LENGTH(`creditDocument`.`customerTown`)>100, concat(left(`creditDocument`.`customerTown`,100),' ...'), `creditDocument`.`customerTown`)" => "customerTown"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`creditDocument`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`creditDocument`.`dateIncomingNote`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`creditDocument`.`id`" => "id",
		"`creditDocument`.`incomingTypeDoc`" => "incomingTypeDoc",
		"`creditDocument`.`customerID`" => "customerID",
		"`creditDocument`.`nrDoc`" => "nrDoc",
		"if(`creditDocument`.`dateIncomingNote`,date_format(`creditDocument`.`dateIncomingNote`,'%Y-%m-%d'),'')" => "dateIncomingNote",
		"`creditDocument`.`customerFirm`" => "customerFirm",
		"`creditDocument`.`customerAddress`" => "customerAddress",
		"`creditDocument`.`customerPostCode`" => "customerPostCode",
		"`creditDocument`.`customerTown`" => "customerTown"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`creditDocument`.`id`" => "ID",
		"`creditDocument`.`incomingTypeDoc`" => "Tipo Documento",
		"`creditDocument`.`customerID`" => "ID Cliente",
		"`creditDocument`.`nrDoc`" => "Nr Doc",
		"`creditDocument`.`dateIncomingNote`" => "Data nota",
		"`creditDocument`.`customerFirm`" => "Ragione Sociale",
		"`creditDocument`.`customerAddress`" => "Indirizzo Cliente",
		"`creditDocument`.`customerPostCode`" => "CAP Cliente",
		"`creditDocument`.`customerTown`" => "Citta cliente"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`creditDocument`.`id`" => "id",
		"`creditDocument`.`incomingTypeDoc`" => "Tipo Documento",
		"`creditDocument`.`customerID`" => "ID Cliente",
		"`creditDocument`.`nrDoc`" => "Nr Doc",
		"if(`creditDocument`.`dateIncomingNote`,date_format(`creditDocument`.`dateIncomingNote`,'%Y-%m-%d'),'')" => "dateIncomingNote",
		"`creditDocument`.`customerFirm`" => "Ragione Sociale",
		"`creditDocument`.`customerAddress`" => "Indirizzo Cliente",
		"`creditDocument`.`customerPostCode`" => "CAP Cliente",
		"`creditDocument`.`customerTown`" => "Citta cliente"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`creditDocument` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "creditDocument_view.php";
	$x->RedirectAfterInsert = "creditDocument_view.php?SelectedID=#ID#";
	$x->TableTitle = "Nota Credito";
	$x->TableIcon = "resources/table_icons/card_credit.png";
	$x->PrimaryKey = "`creditDocument`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Tipo Documento", "ID Cliente", "Nr Doc", "Data nota", "Ragione Sociale", "Indirizzo Cliente", "CAP Cliente", "Citta cliente");
	$x->ColFieldName = array('incomingTypeDoc', 'customerID', 'nrDoc', 'dateIncomingNote', 'customerFirm', 'customerAddress', 'customerPostCode', 'customerTown');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/creditDocument_templateTV.html';
	$x->SelectedTemplate = 'templates/creditDocument_templateTVS.html';
	$x->TemplateDV = 'templates/creditDocument_templateDV.html';
	$x->TemplateDVP = 'templates/creditDocument_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `creditDocument`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='creditDocument' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `creditDocument`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='creditDocument' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`creditDocument`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: creditDocument_init
	$render=TRUE;
	if(function_exists('creditDocument_init')){
		$args=array();
		$render=creditDocument_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: creditDocument_header
	$headerCode='';
	if(function_exists('creditDocument_header')){
		$args=array();
		$headerCode=creditDocument_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: creditDocument_footer
	$footerCode='';
	if(function_exists('creditDocument_footer')){
		$args=array();
		$footerCode=creditDocument_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>