<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/firstCashNote.php");
	include("$currDir/firstCashNote_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('firstCashNote');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "firstCashNote";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`firstCashNote`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"IF(    CHAR_LENGTH(`orders1`.`multiOrder_nr_PA`) || CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `orders1`.`multiOrder_nr_PA`, ' - ', `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* Order */" => "order",
		"if(`firstCashNote`.`operationDate`,date_format(`firstCashNote`.`operationDate`,'%Y-%m-%d'),'')" => "operationDate",
		"IF(    CHAR_LENGTH(`companies2`.`companyCode`) || CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyCode`, ' - ', `companies2`.`companyName`), '') /* Company */" => "company",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Beneficiario Pagamento PA */" => "customer",
		"`firstCashNote`.`documentNumber`" => "documentNumber",
		"`firstCashNote`.`causal`" => "causal",
		"`firstCashNote`.`importoPag_PA`" => "importoPag_PA",
		"`firstCashNote`.`outputs`" => "outputs",
		"`firstCashNote`.`balance`" => "balance",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* IdBank */" => "idBank",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Banca */" => "istitutoFinanziario_PA",
		"`firstCashNote`.`note`" => "note",
		"if(`firstCashNote`.`paymentDeadLine`,date_format(`firstCashNote`.`paymentDeadLine`,'%Y-%m-%d'),'')" => "paymentDeadLine",
		"if(CHAR_LENGTH(`firstCashNote`.`payed`)>100, concat(left(`firstCashNote`.`payed`,100),' ...'), `firstCashNote`.`payed`)" => "payed",
		"`firstCashNote`.`datiPag_PA`" => "datiPag_PA",
		"`firstCashNote`.`modPagam_PA`" => "modPagam_PA",
		"if(`firstCashNote`.`dataRifTerPag_PA`,date_format(`firstCashNote`.`dataRifTerPag_PA`,'%Y-%m-%d'),'')" => "dataRifTerPag_PA",
		"`firstCashNote`.`giorniTermPag_PA`" => "giorniTermPag_PA",
		"if(`firstCashNote`.`dataScadPag_PA`,date_format(`firstCashNote`.`dataScadPag_PA`,'%Y-%m-%d'),'')" => "dataScadPag_PA",
		"`firstCashNote`.`codUffPost_PA`" => "codUffPost_PA",
		"`firstCashNote`.`cognomeQuietanzante_PA`" => "cognomeQuietanzante_PA",
		"`firstCashNote`.`nomeQuietanzante_PA`" => "nomeQuietanzante_PA",
		"`firstCashNote`.`codFiscQuietanzante_PA`" => "codFiscQuietanzante_PA",
		"`firstCashNote`.`titoloQuietanzante_PA`" => "titoloQuietanzante_PA"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`firstCashNote`.`id`',
		2 => '`kinds1`.`name`',
		3 => 3,
		4 => '`firstCashNote`.`operationDate`',
		5 => 5,
		6 => '`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`',
		7 => '`firstCashNote`.`documentNumber`',
		8 => 8,
		9 => '`firstCashNote`.`importoPag_PA`',
		10 => '`firstCashNote`.`outputs`',
		11 => '`firstCashNote`.`balance`',
		12 => '`companies2`.`companyName`',
		13 => '`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`',
		14 => 14,
		15 => '`firstCashNote`.`paymentDeadLine`',
		16 => 16,
		17 => 17,
		18 => 18,
		19 => '`firstCashNote`.`dataRifTerPag_PA`',
		20 => '`firstCashNote`.`giorniTermPag_PA`',
		21 => '`firstCashNote`.`dataScadPag_PA`',
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`firstCashNote`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"IF(    CHAR_LENGTH(`orders1`.`multiOrder_nr_PA`) || CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `orders1`.`multiOrder_nr_PA`, ' - ', `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* Order */" => "order",
		"if(`firstCashNote`.`operationDate`,date_format(`firstCashNote`.`operationDate`,'%Y-%m-%d'),'')" => "operationDate",
		"IF(    CHAR_LENGTH(`companies2`.`companyCode`) || CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyCode`, ' - ', `companies2`.`companyName`), '') /* Company */" => "company",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Beneficiario Pagamento PA */" => "customer",
		"`firstCashNote`.`documentNumber`" => "documentNumber",
		"`firstCashNote`.`causal`" => "causal",
		"`firstCashNote`.`importoPag_PA`" => "importoPag_PA",
		"`firstCashNote`.`outputs`" => "outputs",
		"`firstCashNote`.`balance`" => "balance",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* IdBank */" => "idBank",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Banca */" => "istitutoFinanziario_PA",
		"`firstCashNote`.`note`" => "note",
		"if(`firstCashNote`.`paymentDeadLine`,date_format(`firstCashNote`.`paymentDeadLine`,'%Y-%m-%d'),'')" => "paymentDeadLine",
		"`firstCashNote`.`payed`" => "payed",
		"`firstCashNote`.`datiPag_PA`" => "datiPag_PA",
		"`firstCashNote`.`modPagam_PA`" => "modPagam_PA",
		"if(`firstCashNote`.`dataRifTerPag_PA`,date_format(`firstCashNote`.`dataRifTerPag_PA`,'%Y-%m-%d'),'')" => "dataRifTerPag_PA",
		"`firstCashNote`.`giorniTermPag_PA`" => "giorniTermPag_PA",
		"if(`firstCashNote`.`dataScadPag_PA`,date_format(`firstCashNote`.`dataScadPag_PA`,'%Y-%m-%d'),'')" => "dataScadPag_PA",
		"`firstCashNote`.`codUffPost_PA`" => "codUffPost_PA",
		"`firstCashNote`.`cognomeQuietanzante_PA`" => "cognomeQuietanzante_PA",
		"`firstCashNote`.`nomeQuietanzante_PA`" => "nomeQuietanzante_PA",
		"`firstCashNote`.`codFiscQuietanzante_PA`" => "codFiscQuietanzante_PA",
		"`firstCashNote`.`titoloQuietanzante_PA`" => "titoloQuietanzante_PA"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`firstCashNote`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "Kind",
		"IF(    CHAR_LENGTH(`orders1`.`multiOrder_nr_PA`) || CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `orders1`.`multiOrder_nr_PA`, ' - ', `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* Order */" => "Order",
		"`firstCashNote`.`operationDate`" => "Data operazione",
		"IF(    CHAR_LENGTH(`companies2`.`companyCode`) || CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyCode`, ' - ', `companies2`.`companyName`), '') /* Company */" => "Company",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Beneficiario Pagamento PA */" => "Beneficiario Pagamento PA",
		"`firstCashNote`.`documentNumber`" => "Numero ordine",
		"`firstCashNote`.`causal`" => "Causale",
		"`firstCashNote`.`importoPag_PA`" => "Importo Pag. PA",
		"`firstCashNote`.`outputs`" => "Uscite",
		"`firstCashNote`.`balance`" => "Bilancio",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* IdBank */" => "IdBank",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Banca */" => "Banca",
		"`firstCashNote`.`note`" => "Note pagamento",
		"`firstCashNote`.`paymentDeadLine`" => "Pagamento in data",
		"`firstCashNote`.`payed`" => "Pagato SI/NO",
		"`firstCashNote`.`datiPag_PA`" => "Condizioni Pag PA",
		"`firstCashNote`.`modPagam_PA`" => "ModPagam PA",
		"`firstCashNote`.`dataRifTerPag_PA`" => "Data Rif. Termini Pag. PA",
		"`firstCashNote`.`giorniTermPag_PA`" => "Giorni Termini Pag. PA",
		"`firstCashNote`.`dataScadPag_PA`" => "Data Scad. Pag. PA",
		"`firstCashNote`.`codUffPost_PA`" => "Cod. Uff. Post. PA",
		"`firstCashNote`.`cognomeQuietanzante_PA`" => "CognomeQuietanzante PA",
		"`firstCashNote`.`nomeQuietanzante_PA`" => "NomeQuietanzante PA",
		"`firstCashNote`.`codFiscQuietanzante_PA`" => "CodFiscQuietanzante PA",
		"`firstCashNote`.`titoloQuietanzante_PA`" => "TitoloQuietanzante PA"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`firstCashNote`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"IF(    CHAR_LENGTH(`orders1`.`multiOrder_nr_PA`) || CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `orders1`.`multiOrder_nr_PA`, ' - ', `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* Order */" => "order",
		"if(`firstCashNote`.`operationDate`,date_format(`firstCashNote`.`operationDate`,'%Y-%m-%d'),'')" => "operationDate",
		"IF(    CHAR_LENGTH(`companies2`.`companyCode`) || CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyCode`, ' - ', `companies2`.`companyName`), '') /* Company */" => "company",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Beneficiario Pagamento PA */" => "customer",
		"`firstCashNote`.`documentNumber`" => "documentNumber",
		"`firstCashNote`.`causal`" => "causal",
		"`firstCashNote`.`importoPag_PA`" => "importoPag_PA",
		"`firstCashNote`.`outputs`" => "outputs",
		"`firstCashNote`.`balance`" => "balance",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* IdBank */" => "idBank",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`Denominazione_Ces_PA`), '') /* Banca */" => "istitutoFinanziario_PA",
		"`firstCashNote`.`note`" => "note",
		"if(`firstCashNote`.`paymentDeadLine`,date_format(`firstCashNote`.`paymentDeadLine`,'%Y-%m-%d'),'')" => "paymentDeadLine",
		"`firstCashNote`.`payed`" => "Pagato SI/NO",
		"`firstCashNote`.`datiPag_PA`" => "datiPag_PA",
		"`firstCashNote`.`modPagam_PA`" => "modPagam_PA",
		"if(`firstCashNote`.`dataRifTerPag_PA`,date_format(`firstCashNote`.`dataRifTerPag_PA`,'%Y-%m-%d'),'')" => "dataRifTerPag_PA",
		"`firstCashNote`.`giorniTermPag_PA`" => "giorniTermPag_PA",
		"if(`firstCashNote`.`dataScadPag_PA`,date_format(`firstCashNote`.`dataScadPag_PA`,'%Y-%m-%d'),'')" => "dataScadPag_PA",
		"`firstCashNote`.`codUffPost_PA`" => "codUffPost_PA",
		"`firstCashNote`.`cognomeQuietanzante_PA`" => "cognomeQuietanzante_PA",
		"`firstCashNote`.`nomeQuietanzante_PA`" => "nomeQuietanzante_PA",
		"`firstCashNote`.`codFiscQuietanzante_PA`" => "codFiscQuietanzante_PA",
		"`firstCashNote`.`titoloQuietanzante_PA`" => "titoloQuietanzante_PA"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'kind' => 'Kind', 'order' => 'Order', 'customer' => 'Beneficiario Pagamento PA', 'idBank' => 'IdBank');

	$x->QueryFrom = "`firstCashNote` LEFT JOIN `kinds` as kinds1 ON `kinds1`.`code`=`firstCashNote`.`kind` LEFT JOIN `orders` as orders1 ON `orders1`.`id`=`firstCashNote`.`order` LEFT JOIN `companies` as companies1 ON `companies1`.`id`=`orders1`.`company` LEFT JOIN `CLIENTI_CESSIONARI_PA` as CLIENTI_CESSIONARI_PA1 ON `CLIENTI_CESSIONARI_PA1`.`id`=`firstCashNote`.`customer` LEFT JOIN `companies` as companies2 ON `companies2`.`id`=`firstCashNote`.`idBank` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "firstCashNote_view.php";
	$x->RedirectAfterInsert = "firstCashNote_view.php?SelectedID=#ID#";
	$x->TableTitle = "Prima Nota";
	$x->TableIcon = "resources/table_icons/data_sort.png";
	$x->PrimaryKey = "`firstCashNote`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Kind", "Order", "Data operazione", "Company", "Beneficiario Pagamento PA", "Numero ordine", "Causale", "Importo Pag. PA", "Uscite", "Bilancio", "Banca", "Note pagamento", "Pagamento in data", "Pagato SI/NO", "Condizioni Pag PA", "ModPagam PA", "Data Rif. Termini Pag. PA", "Giorni Termini Pag. PA", "Data Scad. Pag. PA");
	$x->ColFieldName = array('kind', 'order', 'operationDate', 'company', 'customer', 'documentNumber', 'causal', 'importoPag_PA', 'outputs', 'balance', 'istitutoFinanziario_PA', 'note', 'paymentDeadLine', 'payed', 'datiPag_PA', 'modPagam_PA', 'dataRifTerPag_PA', 'giorniTermPag_PA', 'dataScadPag_PA');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21);

	// template paths below are based on the app main directory
	$x->Template = 'templates/firstCashNote_templateTV.html';
	$x->SelectedTemplate = 'templates/firstCashNote_templateTVS.html';
	$x->TemplateDV = 'templates/firstCashNote_templateDV.html';
	$x->TemplateDVP = 'templates/firstCashNote_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `firstCashNote`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='firstCashNote' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `firstCashNote`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='firstCashNote' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`firstCashNote`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: firstCashNote_init
	$render=TRUE;
	if(function_exists('firstCashNote_init')){
		$args=array();
		$render=firstCashNote_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])){
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id){   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != ''){
				$QueryWhere = 'where `firstCashNote`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "select sum(`firstCashNote`.`importoPag_PA`), sum(`firstCashNote`.`outputs`), sum(`firstCashNote`.`balance`) from {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)){
			$sumRow = '<tr class="success">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<td class="text-center"><strong>&sum;</strong></td>';
			$sumRow .= '<td class="firstCashNote-kind"></td>';
			$sumRow .= '<td class="firstCashNote-order"></td>';
			$sumRow .= '<td class="firstCashNote-operationDate"></td>';
			$sumRow .= '<td class="firstCashNote-company"></td>';
			$sumRow .= '<td class="firstCashNote-customer"></td>';
			$sumRow .= '<td class="firstCashNote-documentNumber"></td>';
			$sumRow .= '<td class="firstCashNote-causal"></td>';
			$sumRow .= "<td class=\"firstCashNote-importoPag_PA text-right\">{$row[0]}</td>";
			$sumRow .= "<td class=\"firstCashNote-outputs text-right\">{$row[1]}</td>";
			$sumRow .= "<td class=\"firstCashNote-balance text-right\">{$row[2]}</td>";
			$sumRow .= '<td class="firstCashNote-istitutoFinanziario_PA"></td>';
			$sumRow .= '<td class="firstCashNote-note"></td>';
			$sumRow .= '<td class="firstCashNote-paymentDeadLine"></td>';
			$sumRow .= '<td class="firstCashNote-payed"></td>';
			$sumRow .= '<td class="firstCashNote-datiPag_PA"></td>';
			$sumRow .= '<td class="firstCashNote-modPagam_PA"></td>';
			$sumRow .= '<td class="firstCashNote-dataRifTerPag_PA"></td>';
			$sumRow .= '<td class="firstCashNote-giorniTermPag_PA"></td>';
			$sumRow .= '<td class="firstCashNote-dataScadPag_PA"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: firstCashNote_header
	$headerCode='';
	if(function_exists('firstCashNote_header')){
		$args=array();
		$headerCode=firstCashNote_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: firstCashNote_footer
	$footerCode='';
	if(function_exists('firstCashNote_footer')){
		$args=array();
		$footerCode=firstCashNote_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>