<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/orders.php");
	include("$currDir/orders_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('orders');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "orders";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`orders`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"`orders`.`progressivNumber`" => "progressivNumber",
		"`orders`.`consigneeID`" => "consigneeID",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* ID Azienda */" => "company",
		"IF(    CHAR_LENGTH(`kinds2`.`code`) || CHAR_LENGTH(`kinds2`.`name`), CONCAT_WS('',   `kinds2`.`code`, ' - ', `kinds2`.`name`), '') /* Documento */" => "typeDoc",
		"`orders`.`multiOrder_nr_PA`" => "multiOrder_nr_PA",
		"`orders`.`formatoTrasmissione_PA`" => "formatoTrasmissione_PA",
		"`orders`.`tipo_Documento_PA`" => "tipo_Documento_PA",
		"`orders`.`divisa_PA`" => "divisa_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`importo_Sc_Mg_PA`, 2))" => "importo_Sc_Mg_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`importoTot_Doc_PA`, 2))" => "importoTot_Doc_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`arrotondamento_PA`, 2))" => "arrotondamento_PA",
		"`orders`.`causale_PA`" => "causale_PA",
		"`orders`.`art73_PA`" => "art73_PA",
		"if(`orders`.`data_Ord_PA`,date_format(`orders`.`data_Ord_PA`,'%Y-%m-%d'),'')" => "data_Ord_PA",
		"if(`orders`.`dataOraRit_PA`,date_format(`orders`.`dataOraRit_PA`,'%Y-%m-%d'),'')" => "dataOraRit_PA",
		"if(`orders`.`dataInizTrasp_PA`,date_format(`orders`.`dataInizTrasp_PA`,'%Y-%m-%d'),'')" => "dataInizTrasp_PA",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* Cliente */" => "customer",
		"IF(    CHAR_LENGTH(`companies3`.`companyName`), CONCAT_WS('',   `companies3`.`companyName`), '') /* Fornitore */" => "supplier",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), '') /* Impiegato */" => "employee",
		"IF(    CHAR_LENGTH(`companies4`.`companyName`), CONCAT_WS('',   `companies4`.`companyName`), '') /* Spedizione a mezzo */" => "shipVia",
		"`orders`.`Freight`" => "Freight",
		"`orders`.`pallets`" => "pallets",
		"if(CHAR_LENGTH(`orders`.`mezzoTraspVet_PA`)>80, concat(left(`orders`.`mezzoTraspVet_PA`,80),' ...'), `orders`.`mezzoTraspVet_PA`)" => "mezzoTraspVet_PA",
		"`orders`.`causaleTraspVet_PA`" => "causaleTraspVet_PA",
		"`orders`.`nrColliVett_PA`" => "nrColliVett_PA",
		"`orders`.`descTraspVet_PA`" => "descTraspVet_PA",
		"concat('<i class=\"glyphicon glyphicon-', if(`orders`.`cashCredit`, 'check', 'unchecked'), '\"></i>')" => "cashCredit",
		"`orders`.`trust`" => "trust",
		"`orders`.`overdraft`" => "overdraft",
		"`orders`.`commisionFee`" => "commisionFee",
		"`orders`.`commisionRate`" => "commisionRate",
		"`orders`.`related`" => "related",
		"`orders`.`document`" => "document",
		"`orders`.`tipo_rit_PA`" => "tipo_rit_PA",
		"`orders`.`imp_rit_PA`" => "imp_rit_PA",
		"FORMAT(`orders`.`aliq_rit_PA`, 2)" => "aliq_rit_PA",
		"`orders`.`causale_pag_rit_PA`" => "causale_pag_rit_PA",
		"`orders`.`nr_bollo_rit_PA`" => "nr_bollo_rit_PA",
		"FORMAT(`orders`.`importo_Bollo_rit_PA`, 2)" => "importo_Bollo_rit_PA",
		"`orders`.`tipo_cassa_Prev_PA`" => "tipo_cassa_Prev_PA",
		"FORMAT(`orders`.`al_cassa_Prev_PA`, 2)" => "al_cassa_Prev_PA",
		"FORMAT(`orders`.`importo_cont_cassa_prev_PA`, 2)" => "importo_cont_cassa_prev_PA",
		"FORMAT(`orders`.`imponibile_cassa_Prev_PA`, 2)" => "imponibile_cassa_Prev_PA",
		"FORMAT(`orders`.`aliq_IVA_cassa_prev_PA`, 2)" => "aliq_IVA_cassa_prev_PA",
		"`orders`.`ritenuta_cassa_prev_PA`" => "ritenuta_cassa_prev_PA",
		"`orders`.`natura_cassa_prev_PA`" => "natura_cassa_prev_PA",
		"`orders`.`rif_amm_prev_PA`" => "rif_amm_prev_PA",
		"`orders`.`tipoResa_PA`" => "tipoResa_PA",
		"`orders`.`indirizzoResa_PA`" => "indirizzoResa_PA",
		"`orders`.`nrCivicoResa_PA`" => "nrCivicoResa_PA",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* CAP Resa PA */" => "CAP_Resa_PA",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* ComuneResa PA */" => "comuneResa_PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* ProvResa PA */" => "provResa_PA",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* NazioneResa PA */" => "nazioneResa_PA",
		"if(`orders`.`dataOraCons_PA`,date_format(`orders`.`dataOraCons_PA`,'%Y-%m-%d'),'')" => "dataOraCons_PA"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`orders`.`id`',
		2 => '`kinds1`.`name`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`orders`.`multiOrder_nr_PA`',
		8 => 8,
		9 => 9,
		10 => 10,
		11 => '`orders`.`importo_Sc_Mg_PA`',
		12 => '`orders`.`importoTot_Doc_PA`',
		13 => '`orders`.`arrotondamento_PA`',
		14 => 14,
		15 => 15,
		16 => '`orders`.`data_Ord_PA`',
		17 => '`orders`.`dataOraRit_PA`',
		18 => '`orders`.`dataInizTrasp_PA`',
		19 => '`companies2`.`companyName`',
		20 => '`companies3`.`companyName`',
		21 => '`CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`',
		22 => '`companies4`.`companyName`',
		23 => '`orders`.`Freight`',
		24 => '`orders`.`pallets`',
		25 => 25,
		26 => 26,
		27 => '`orders`.`nrColliVett_PA`',
		28 => 28,
		29 => 29,
		30 => '`orders`.`trust`',
		31 => '`orders`.`overdraft`',
		32 => '`orders`.`commisionFee`',
		33 => '`orders`.`commisionRate`',
		34 => '`orders`.`related`',
		35 => 35,
		36 => 36,
		37 => 37,
		38 => '`orders`.`aliq_rit_PA`',
		39 => 39,
		40 => 40,
		41 => 41,
		42 => 42,
		43 => '`orders`.`al_cassa_Prev_PA`',
		44 => '`orders`.`importo_cont_cassa_prev_PA`',
		45 => '`orders`.`imponibile_cassa_Prev_PA`',
		46 => '`orders`.`aliq_IVA_cassa_prev_PA`',
		47 => 47,
		48 => 48,
		49 => 49,
		50 => 50,
		51 => 51,
		52 => 52,
		53 => '`town1`.`shipCode`',
		54 => '`town1`.`town`',
		55 => '`town1`.`district`',
		56 => '`countries1`.`code`',
		57 => '`orders`.`dataOraCons_PA`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`orders`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"`orders`.`progressivNumber`" => "progressivNumber",
		"`orders`.`consigneeID`" => "consigneeID",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* ID Azienda */" => "company",
		"IF(    CHAR_LENGTH(`kinds2`.`code`) || CHAR_LENGTH(`kinds2`.`name`), CONCAT_WS('',   `kinds2`.`code`, ' - ', `kinds2`.`name`), '') /* Documento */" => "typeDoc",
		"`orders`.`multiOrder_nr_PA`" => "multiOrder_nr_PA",
		"`orders`.`formatoTrasmissione_PA`" => "formatoTrasmissione_PA",
		"`orders`.`tipo_Documento_PA`" => "tipo_Documento_PA",
		"`orders`.`divisa_PA`" => "divisa_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`importo_Sc_Mg_PA`, 2))" => "importo_Sc_Mg_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`importoTot_Doc_PA`, 2))" => "importoTot_Doc_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`arrotondamento_PA`, 2))" => "arrotondamento_PA",
		"`orders`.`causale_PA`" => "causale_PA",
		"`orders`.`art73_PA`" => "art73_PA",
		"if(`orders`.`data_Ord_PA`,date_format(`orders`.`data_Ord_PA`,'%Y-%m-%d'),'')" => "data_Ord_PA",
		"if(`orders`.`dataOraRit_PA`,date_format(`orders`.`dataOraRit_PA`,'%Y-%m-%d'),'')" => "dataOraRit_PA",
		"if(`orders`.`dataInizTrasp_PA`,date_format(`orders`.`dataInizTrasp_PA`,'%Y-%m-%d'),'')" => "dataInizTrasp_PA",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* Cliente */" => "customer",
		"IF(    CHAR_LENGTH(`companies3`.`companyName`), CONCAT_WS('',   `companies3`.`companyName`), '') /* Fornitore */" => "supplier",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), '') /* Impiegato */" => "employee",
		"IF(    CHAR_LENGTH(`companies4`.`companyName`), CONCAT_WS('',   `companies4`.`companyName`), '') /* Spedizione a mezzo */" => "shipVia",
		"`orders`.`Freight`" => "Freight",
		"`orders`.`pallets`" => "pallets",
		"`orders`.`mezzoTraspVet_PA`" => "mezzoTraspVet_PA",
		"`orders`.`causaleTraspVet_PA`" => "causaleTraspVet_PA",
		"`orders`.`nrColliVett_PA`" => "nrColliVett_PA",
		"`orders`.`descTraspVet_PA`" => "descTraspVet_PA",
		"`orders`.`cashCredit`" => "cashCredit",
		"`orders`.`trust`" => "trust",
		"`orders`.`overdraft`" => "overdraft",
		"`orders`.`commisionFee`" => "commisionFee",
		"`orders`.`commisionRate`" => "commisionRate",
		"`orders`.`related`" => "related",
		"`orders`.`document`" => "document",
		"`orders`.`tipo_rit_PA`" => "tipo_rit_PA",
		"`orders`.`imp_rit_PA`" => "imp_rit_PA",
		"FORMAT(`orders`.`aliq_rit_PA`, 2)" => "aliq_rit_PA",
		"`orders`.`causale_pag_rit_PA`" => "causale_pag_rit_PA",
		"`orders`.`nr_bollo_rit_PA`" => "nr_bollo_rit_PA",
		"FORMAT(`orders`.`importo_Bollo_rit_PA`, 2)" => "importo_Bollo_rit_PA",
		"`orders`.`tipo_cassa_Prev_PA`" => "tipo_cassa_Prev_PA",
		"FORMAT(`orders`.`al_cassa_Prev_PA`, 2)" => "al_cassa_Prev_PA",
		"FORMAT(`orders`.`importo_cont_cassa_prev_PA`, 2)" => "importo_cont_cassa_prev_PA",
		"FORMAT(`orders`.`imponibile_cassa_Prev_PA`, 2)" => "imponibile_cassa_Prev_PA",
		"FORMAT(`orders`.`aliq_IVA_cassa_prev_PA`, 2)" => "aliq_IVA_cassa_prev_PA",
		"`orders`.`ritenuta_cassa_prev_PA`" => "ritenuta_cassa_prev_PA",
		"`orders`.`natura_cassa_prev_PA`" => "natura_cassa_prev_PA",
		"`orders`.`rif_amm_prev_PA`" => "rif_amm_prev_PA",
		"`orders`.`tipoResa_PA`" => "tipoResa_PA",
		"`orders`.`indirizzoResa_PA`" => "indirizzoResa_PA",
		"`orders`.`nrCivicoResa_PA`" => "nrCivicoResa_PA",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* CAP Resa PA */" => "CAP_Resa_PA",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* ComuneResa PA */" => "comuneResa_PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* ProvResa PA */" => "provResa_PA",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* NazioneResa PA */" => "nazioneResa_PA",
		"if(`orders`.`dataOraCons_PA`,date_format(`orders`.`dataOraCons_PA`,'%Y-%m-%d'),'')" => "dataOraCons_PA"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`orders`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "Kind",
		"`orders`.`progressivNumber`" => "Numero progressivo",
		"`orders`.`consigneeID`" => "Codice Destinatario",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* ID Azienda */" => "ID Azienda",
		"IF(    CHAR_LENGTH(`kinds2`.`code`) || CHAR_LENGTH(`kinds2`.`name`), CONCAT_WS('',   `kinds2`.`code`, ' - ', `kinds2`.`name`), '') /* Documento */" => "Documento",
		"`orders`.`multiOrder_nr_PA`" => "Numero",
		"`orders`.`formatoTrasmissione_PA`" => "Formato Trasmissione PA",
		"`orders`.`tipo_Documento_PA`" => "Tipo Documento PA",
		"`orders`.`divisa_PA`" => "Divisa PA",
		"`orders`.`importo_Sc_Mg_PA`" => "Importo Sconto o Mag PA",
		"`orders`.`importoTot_Doc_PA`" => "Importo Totale doc.",
		"`orders`.`arrotondamento_PA`" => "Arrotondamento PA",
		"`orders`.`causale_PA`" => "Causale PA",
		"`orders`.`art73_PA`" => "Art73 PA",
		"`orders`.`data_Ord_PA`" => "Data dell\'ordine PA",
		"`orders`.`dataOraRit_PA`" => "Data Ora Ritiro PA",
		"`orders`.`dataInizTrasp_PA`" => "Data Inizo Trasporto PA",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* Cliente */" => "Cliente",
		"IF(    CHAR_LENGTH(`companies3`.`companyName`), CONCAT_WS('',   `companies3`.`companyName`), '') /* Fornitore */" => "Fornitore",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), '') /* Impiegato */" => "Impiegato",
		"IF(    CHAR_LENGTH(`companies4`.`companyName`), CONCAT_WS('',   `companies4`.`companyName`), '') /* Spedizione a mezzo */" => "Spedizione a mezzo",
		"`orders`.`Freight`" => "Nolo",
		"`orders`.`pallets`" => "Pallets",
		"`orders`.`mezzoTraspVet_PA`" => "Targa Automezzo",
		"`orders`.`causaleTraspVet_PA`" => "CausaleTraspVet PA",
		"`orders`.`nrColliVett_PA`" => "NrColliVett PA",
		"`orders`.`descTraspVet_PA`" => "ASPETTO EST. BENI (DescTraspVet PA)",
		"`orders`.`cashCredit`" => "Credito o cassa",
		"`orders`.`trust`" => "Fido Cliente",
		"`orders`.`overdraft`" => "Scoperto Cliente",
		"`orders`.`commisionFee`" => "Provvigione su ordine",
		"`orders`.`commisionRate`" => "CommisionRate",
		"`orders`.`related`" => "Related",
		"`orders`.`document`" => "Document",
		"`orders`.`tipo_rit_PA`" => "Tipo ritenuta PA",
		"`orders`.`imp_rit_PA`" => "Importo rit. PA",
		"`orders`.`aliq_rit_PA`" => "Aliquota rit. PA",
		"`orders`.`causale_pag_rit_PA`" => "Causale pag. ritenuta PA",
		"`orders`.`nr_bollo_rit_PA`" => "Nr bollo ritenuta PA",
		"`orders`.`importo_Bollo_rit_PA`" => "Importo Bollo ritenuta PA",
		"`orders`.`tipo_cassa_Prev_PA`" => "Tipo cassa previdenza PA",
		"`orders`.`al_cassa_Prev_PA`" => "Aliquota cassa Prev. PA",
		"`orders`.`importo_cont_cassa_prev_PA`" => "Importo cont. cassa prev. PA",
		"`orders`.`imponibile_cassa_Prev_PA`" => "Imponibile cassa Prev PA",
		"`orders`.`aliq_IVA_cassa_prev_PA`" => "Aliq IVA cassa prev PA",
		"`orders`.`ritenuta_cassa_prev_PA`" => "Ritenuta cassa prev PA",
		"`orders`.`natura_cassa_prev_PA`" => "Natura cassa prev PA",
		"`orders`.`rif_amm_prev_PA`" => "Riferimento amministrazione prev PA",
		"`orders`.`tipoResa_PA`" => "TipoResa PA",
		"`orders`.`indirizzoResa_PA`" => "Luogo consegna",
		"`orders`.`nrCivicoResa_PA`" => "NrCivicoResa PA",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* CAP Resa PA */" => "CAP Resa PA",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* ComuneResa PA */" => "ComuneResa PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* ProvResa PA */" => "ProvResa PA",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* NazioneResa PA */" => "NazioneResa PA",
		"`orders`.`dataOraCons_PA`" => "DataOraCons PA"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`orders`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"`orders`.`progressivNumber`" => "Numero progressivo",
		"`orders`.`consigneeID`" => "Codice Destinatario",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`) || CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyCode`, ' - ', `companies1`.`companyName`), '') /* ID Azienda */" => "company",
		"IF(    CHAR_LENGTH(`kinds2`.`code`) || CHAR_LENGTH(`kinds2`.`name`), CONCAT_WS('',   `kinds2`.`code`, ' - ', `kinds2`.`name`), '') /* Documento */" => "typeDoc",
		"`orders`.`multiOrder_nr_PA`" => "multiOrder_nr_PA",
		"`orders`.`formatoTrasmissione_PA`" => "Formato Trasmissione PA",
		"`orders`.`tipo_Documento_PA`" => "tipo_Documento_PA",
		"`orders`.`divisa_PA`" => "divisa_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`importo_Sc_Mg_PA`, 2))" => "importo_Sc_Mg_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`importoTot_Doc_PA`, 2))" => "importoTot_Doc_PA",
		"CONCAT('&euro;', FORMAT(`orders`.`arrotondamento_PA`, 2))" => "arrotondamento_PA",
		"`orders`.`causale_PA`" => "causale_PA",
		"`orders`.`art73_PA`" => "art73_PA",
		"if(`orders`.`data_Ord_PA`,date_format(`orders`.`data_Ord_PA`,'%Y-%m-%d'),'')" => "data_Ord_PA",
		"if(`orders`.`dataOraRit_PA`,date_format(`orders`.`dataOraRit_PA`,'%Y-%m-%d'),'')" => "dataOraRit_PA",
		"if(`orders`.`dataInizTrasp_PA`,date_format(`orders`.`dataInizTrasp_PA`,'%Y-%m-%d'),'')" => "dataInizTrasp_PA",
		"IF(    CHAR_LENGTH(`companies2`.`companyName`), CONCAT_WS('',   `companies2`.`companyName`), '') /* Cliente */" => "customer",
		"IF(    CHAR_LENGTH(`companies3`.`companyName`), CONCAT_WS('',   `companies3`.`companyName`), '') /* Fornitore */" => "supplier",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`nome_Ces_PA`), '') /* Impiegato */" => "employee",
		"IF(    CHAR_LENGTH(`companies4`.`companyName`), CONCAT_WS('',   `companies4`.`companyName`), '') /* Spedizione a mezzo */" => "shipVia",
		"`orders`.`Freight`" => "Freight",
		"`orders`.`pallets`" => "pallets",
		"`orders`.`mezzoTraspVet_PA`" => "Targa Automezzo",
		"`orders`.`causaleTraspVet_PA`" => "causaleTraspVet_PA",
		"`orders`.`nrColliVett_PA`" => "nrColliVett_PA",
		"`orders`.`descTraspVet_PA`" => "descTraspVet_PA",
		"concat('<i class=\"glyphicon glyphicon-', if(`orders`.`cashCredit`, 'check', 'unchecked'), '\"></i>')" => "cashCredit",
		"`orders`.`trust`" => "trust",
		"`orders`.`overdraft`" => "overdraft",
		"`orders`.`commisionFee`" => "commisionFee",
		"`orders`.`commisionRate`" => "commisionRate",
		"`orders`.`related`" => "related",
		"`orders`.`document`" => "document",
		"`orders`.`tipo_rit_PA`" => "tipo_rit_PA",
		"`orders`.`imp_rit_PA`" => "imp_rit_PA",
		"FORMAT(`orders`.`aliq_rit_PA`, 2)" => "aliq_rit_PA",
		"`orders`.`causale_pag_rit_PA`" => "causale_pag_rit_PA",
		"`orders`.`nr_bollo_rit_PA`" => "nr_bollo_rit_PA",
		"FORMAT(`orders`.`importo_Bollo_rit_PA`, 2)" => "importo_Bollo_rit_PA",
		"`orders`.`tipo_cassa_Prev_PA`" => "tipo_cassa_Prev_PA",
		"FORMAT(`orders`.`al_cassa_Prev_PA`, 2)" => "al_cassa_Prev_PA",
		"FORMAT(`orders`.`importo_cont_cassa_prev_PA`, 2)" => "importo_cont_cassa_prev_PA",
		"FORMAT(`orders`.`imponibile_cassa_Prev_PA`, 2)" => "imponibile_cassa_Prev_PA",
		"FORMAT(`orders`.`aliq_IVA_cassa_prev_PA`, 2)" => "aliq_IVA_cassa_prev_PA",
		"`orders`.`ritenuta_cassa_prev_PA`" => "ritenuta_cassa_prev_PA",
		"`orders`.`natura_cassa_prev_PA`" => "natura_cassa_prev_PA",
		"`orders`.`rif_amm_prev_PA`" => "rif_amm_prev_PA",
		"`orders`.`tipoResa_PA`" => "tipoResa_PA",
		"`orders`.`indirizzoResa_PA`" => "indirizzoResa_PA",
		"`orders`.`nrCivicoResa_PA`" => "nrCivicoResa_PA",
		"IF(    CHAR_LENGTH(`town1`.`shipCode`), CONCAT_WS('',   `town1`.`shipCode`), '') /* CAP Resa PA */" => "CAP_Resa_PA",
		"IF(    CHAR_LENGTH(`town1`.`town`), CONCAT_WS('',   `town1`.`town`), '') /* ComuneResa PA */" => "comuneResa_PA",
		"IF(    CHAR_LENGTH(`town1`.`district`), CONCAT_WS('',   `town1`.`district`), '') /* ProvResa PA */" => "provResa_PA",
		"IF(    CHAR_LENGTH(`countries1`.`code`), CONCAT_WS('',   `countries1`.`code`), '') /* NazioneResa PA */" => "nazioneResa_PA",
		"if(`orders`.`dataOraCons_PA`,date_format(`orders`.`dataOraCons_PA`,'%Y-%m-%d'),'')" => "dataOraCons_PA"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'kind' => 'Kind', 'company' => 'ID Azienda', 'typeDoc' => 'Documento', 'customer' => 'Cliente', 'supplier' => 'Fornitore', 'employee' => 'Impiegato', 'shipVia' => 'Spedizione a mezzo', 'CAP_Resa_PA' => 'CAP Resa PA', 'nazioneResa_PA' => 'NazioneResa PA');

	$x->QueryFrom = "`orders` LEFT JOIN `kinds` as kinds1 ON `kinds1`.`code`=`orders`.`kind` LEFT JOIN `companies` as companies1 ON `companies1`.`id`=`orders`.`company` LEFT JOIN `kinds` as kinds2 ON `kinds2`.`code`=`orders`.`typeDoc` LEFT JOIN `companies` as companies2 ON `companies2`.`id`=`orders`.`customer` LEFT JOIN `companies` as companies3 ON `companies3`.`id`=`orders`.`supplier` LEFT JOIN `CLIENTI_CESSIONARI_PA` as CLIENTI_CESSIONARI_PA1 ON `CLIENTI_CESSIONARI_PA1`.`id`=`orders`.`employee` LEFT JOIN `companies` as companies4 ON `companies4`.`id`=`orders`.`shipVia` LEFT JOIN `town` as town1 ON `town1`.`id`=`orders`.`CAP_Resa_PA` LEFT JOIN `countries` as countries1 ON `countries1`.`id`=`orders`.`nazioneResa_PA` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "orders_view.php";
	$x->RedirectAfterInsert = "orders_view.php?SelectedID=#ID#";
	$x->TableTitle = "Ordini";
	$x->TableIcon = "resources/table_icons/cart_remove.png";
	$x->PrimaryKey = "`orders`.`id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 200, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Kind", "ID Azienda", "Documento", "Numero", "Formato Trasmissione PA", "Tipo Documento PA", "Divisa PA", "Importo Sconto o Mag PA", "Importo Totale doc.", "Causale PA", "Data dell'ordine PA", "Data Ora Ritiro PA", "Data Inizo Trasporto PA", "Cliente", "Spedizione a mezzo", "Pallets", "Targa Automezzo", "ASPETTO EST. BENI (DescTraspVet PA)", "Credito o cassa");
	$x->ColFieldName = array('kind', 'company', 'typeDoc', 'multiOrder_nr_PA', 'formatoTrasmissione_PA', 'tipo_Documento_PA', 'divisa_PA', 'importo_Sc_Mg_PA', 'importoTot_Doc_PA', 'causale_PA', 'data_Ord_PA', 'dataOraRit_PA', 'dataInizTrasp_PA', 'customer', 'shipVia', 'pallets', 'mezzoTraspVet_PA', 'descTraspVet_PA', 'cashCredit');
	$x->ColNumber  = array(2, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 17, 18, 19, 22, 24, 25, 28, 29);

	// template paths below are based on the app main directory
	$x->Template = 'templates/orders_templateTV.html';
	$x->SelectedTemplate = 'templates/orders_templateTVS.html';
	$x->TemplateDV = 'templates/orders_templateDV.html';
	$x->TemplateDVP = 'templates/orders_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `orders`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='orders' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `orders`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='orders' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`orders`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: orders_init
	$render=TRUE;
	if(function_exists('orders_init')){
		$args=array();
		$render=orders_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])){
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id){   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != ''){
				$QueryWhere = 'where `orders`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "select CONCAT('&euro;', FORMAT(sum(`orders`.`importoTot_Doc_PA`), 2)), sum(`orders`.`pallets`) from {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)){
			$sumRow = '<tr class="success">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<td class="text-center"><strong>&sum;</strong></td>';
			$sumRow .= '<td class="orders-kind"></td>';
			$sumRow .= '<td class="orders-company"></td>';
			$sumRow .= '<td class="orders-typeDoc"></td>';
			$sumRow .= '<td class="orders-multiOrder_nr_PA"></td>';
			$sumRow .= '<td class="orders-formatoTrasmissione_PA"></td>';
			$sumRow .= '<td class="orders-tipo_Documento_PA"></td>';
			$sumRow .= '<td class="orders-divisa_PA"></td>';
			$sumRow .= '<td class="orders-importo_Sc_Mg_PA"></td>';
			$sumRow .= "<td class=\"orders-importoTot_Doc_PA text-right\">{$row[0]}</td>";
			$sumRow .= '<td class="orders-causale_PA"></td>';
			$sumRow .= '<td class="orders-data_Ord_PA"></td>';
			$sumRow .= '<td class="orders-dataOraRit_PA"></td>';
			$sumRow .= '<td class="orders-dataInizTrasp_PA"></td>';
			$sumRow .= '<td class="orders-customer"></td>';
			$sumRow .= '<td class="orders-shipVia"></td>';
			$sumRow .= "<td class=\"orders-pallets text-right\">{$row[1]}</td>";
			$sumRow .= '<td class="orders-mezzoTraspVet_PA"></td>';
			$sumRow .= '<td class="orders-descTraspVet_PA"></td>';
			$sumRow .= '<td class="orders-cashCredit"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: orders_header
	$headerCode='';
	if(function_exists('orders_header')){
		$args=array();
		$headerCode=orders_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: orders_footer
	$footerCode='';
	if(function_exists('orders_footer')){
		$args=array();
		$footerCode=orders_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>