<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/phones.php");
	include("$currDir/phones_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('phones');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "phones";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`phones`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"if(CHAR_LENGTH(`phones`.`phoneNumber`)>100, concat(left(`phones`.`phoneNumber`,100),' ...'), `phones`.`phoneNumber`)" => "phoneNumber",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`id`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`id`), '') /* Contact */" => "contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "company"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`phones`.`id`',
		2 => '`kinds1`.`name`',
		3 => 3,
		4 => '`CLIENTI_CESSIONARI_PA1`.`id`',
		5 => '`companies1`.`id`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`phones`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"`phones`.`phoneNumber`" => "phoneNumber",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`id`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`id`), '') /* Contact */" => "contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "company"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`phones`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "Kind",
		"`phones`.`phoneNumber`" => "PhoneNumber",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`id`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`id`), '') /* Contact */" => "Contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "Company"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`phones`.`id`" => "id",
		"IF(    CHAR_LENGTH(`kinds1`.`name`), CONCAT_WS('',   `kinds1`.`name`), '') /* Kind */" => "kind",
		"`phones`.`phoneNumber`" => "PhoneNumber",
		"IF(    CHAR_LENGTH(`CLIENTI_CESSIONARI_PA1`.`id`), CONCAT_WS('',   `CLIENTI_CESSIONARI_PA1`.`id`), '') /* Contact */" => "contact",
		"IF(    CHAR_LENGTH(`companies1`.`id`), CONCAT_WS('',   `companies1`.`id`), '') /* Company */" => "company"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'kind' => 'Kind', 'contact' => 'Contact', 'company' => 'Company');

	$x->QueryFrom = "`phones` LEFT JOIN `kinds` as kinds1 ON `kinds1`.`code`=`phones`.`kind` LEFT JOIN `CLIENTI_CESSIONARI_PA` as CLIENTI_CESSIONARI_PA1 ON `CLIENTI_CESSIONARI_PA1`.`id`=`phones`.`contact` LEFT JOIN `companies` as companies1 ON `companies1`.`id`=`phones`.`company` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "phones_view.php";
	$x->RedirectAfterInsert = "phones_view.php?SelectedID=#ID#";
	$x->TableTitle = "Phones";
	$x->TableIcon = "resources/table_icons/phone.png";
	$x->PrimaryKey = "`phones`.`id`";

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("Kind", "PhoneNumber");
	$x->ColFieldName = array('kind', 'phoneNumber');
	$x->ColNumber  = array(2, 3);

	// template paths below are based on the app main directory
	$x->Template = 'templates/phones_templateTV.html';
	$x->SelectedTemplate = 'templates/phones_templateTVS.html';
	$x->TemplateDV = 'templates/phones_templateDV.html';
	$x->TemplateDVP = 'templates/phones_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `phones`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='phones' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `phones`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='phones' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`phones`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: phones_init
	$render=TRUE;
	if(function_exists('phones_init')){
		$args=array();
		$render=phones_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: phones_header
	$headerCode='';
	if(function_exists('phones_header')){
		$args=array();
		$headerCode=phones_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: phones_footer
	$footerCode='';
	if(function_exists('phones_footer')){
		$args=array();
		$footerCode=phones_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>