<?php
// This script and data application were generated by AppGini 5.74
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/vatRegister.php");
	include("$currDir/vatRegister_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('vatRegister');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "vatRegister";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`vatRegister`.`id`" => "id",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`), CONCAT_WS('',   `companies1`.`companyCode`), '') /* ID Azienda */" => "idCompany",
		"IF(    CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyName`), '') /* Nome Societ&#224; */" => "companyName",
		"`vatRegister`.`tax`" => "tax",
		"`vatRegister`.`month`" => "month",
		"`vatRegister`.`year`" => "year",
		"`vatRegister`.`amount`" => "amount",
		"`vatRegister`.`ufficio_Ced_PA`" => "ufficio_Ced_PA",
		"`vatRegister`.`numeroREA_Ced_PA`" => "numeroREA_Ced_PA",
		"`vatRegister`.`capitaleSociale_Ced_PA`" => "capitaleSociale_Ced_PA",
		"`vatRegister`.`socioUnico_Ced_PA`" => "socioUnico_Ced_PA",
		"`vatRegister`.`statoLiquidazione_Ced_PA`" => "statoLiquidazione_Ced_PA"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`vatRegister`.`id`',
		2 => '`companies1`.`companyCode`',
		3 => '`companies1`.`companyName`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`vatRegister`.`amount`',
		8 => 8,
		9 => 9,
		10 => '`vatRegister`.`capitaleSociale_Ced_PA`',
		11 => 11,
		12 => 12
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`vatRegister`.`id`" => "id",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`), CONCAT_WS('',   `companies1`.`companyCode`), '') /* ID Azienda */" => "idCompany",
		"IF(    CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyName`), '') /* Nome Societ&#224; */" => "companyName",
		"`vatRegister`.`tax`" => "tax",
		"`vatRegister`.`month`" => "month",
		"`vatRegister`.`year`" => "year",
		"`vatRegister`.`amount`" => "amount",
		"`vatRegister`.`ufficio_Ced_PA`" => "ufficio_Ced_PA",
		"`vatRegister`.`numeroREA_Ced_PA`" => "numeroREA_Ced_PA",
		"`vatRegister`.`capitaleSociale_Ced_PA`" => "capitaleSociale_Ced_PA",
		"`vatRegister`.`socioUnico_Ced_PA`" => "socioUnico_Ced_PA",
		"`vatRegister`.`statoLiquidazione_Ced_PA`" => "statoLiquidazione_Ced_PA"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`vatRegister`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`), CONCAT_WS('',   `companies1`.`companyCode`), '') /* ID Azienda */" => "ID Azienda",
		"IF(    CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyName`), '') /* Nome Societ&#224; */" => "Nome Societ&#224;",
		"`vatRegister`.`tax`" => "Aliquota riferimento",
		"`vatRegister`.`month`" => "Mese corrispettivi",
		"`vatRegister`.`year`" => "Anno",
		"`vatRegister`.`amount`" => "Importo",
		"`vatRegister`.`ufficio_Ced_PA`" => "Ufficio Cedente PA",
		"`vatRegister`.`numeroREA_Ced_PA`" => "Numero Iscr. REA PA",
		"`vatRegister`.`capitaleSociale_Ced_PA`" => "Capitale Sociale Ced. PA",
		"`vatRegister`.`socioUnico_Ced_PA`" => "Socio Unico Ced. PA",
		"`vatRegister`.`statoLiquidazione_Ced_PA`" => "Stato Liquidazione"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`vatRegister`.`id`" => "id",
		"IF(    CHAR_LENGTH(`companies1`.`companyCode`), CONCAT_WS('',   `companies1`.`companyCode`), '') /* ID Azienda */" => "idCompany",
		"IF(    CHAR_LENGTH(`companies1`.`companyName`), CONCAT_WS('',   `companies1`.`companyName`), '') /* Nome Societ&#224; */" => "companyName",
		"`vatRegister`.`tax`" => "tax",
		"`vatRegister`.`month`" => "month",
		"`vatRegister`.`year`" => "year",
		"`vatRegister`.`amount`" => "amount",
		"`vatRegister`.`ufficio_Ced_PA`" => "ufficio_Ced_PA",
		"`vatRegister`.`numeroREA_Ced_PA`" => "numeroREA_Ced_PA",
		"`vatRegister`.`capitaleSociale_Ced_PA`" => "capitaleSociale_Ced_PA",
		"`vatRegister`.`socioUnico_Ced_PA`" => "socioUnico_Ced_PA",
		"`vatRegister`.`statoLiquidazione_Ced_PA`" => "statoLiquidazione_Ced_PA"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'idCompany' => 'ID Azienda');

	$x->QueryFrom = "`vatRegister` LEFT JOIN `companies` as companies1 ON `companies1`.`id`=`vatRegister`.`idCompany` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "vatRegister_view.php";
	$x->RedirectAfterInsert = "vatRegister_view.php?SelectedID=#ID#";
	$x->TableTitle = "IscrizioneREA/IVA";
	$x->TableIcon = "resources/table_icons/book_spelling.png";
	$x->PrimaryKey = "`vatRegister`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("ID Azienda", "Nome Societ&#224;", "Aliquota riferimento", "Mese corrispettivi", "Anno", "Importo", "Ufficio Cedente PA", "Numero Iscr. REA PA", "Capitale Sociale Ced. PA", "Socio Unico Ced. PA", "Stato Liquidazione");
	$x->ColFieldName = array('idCompany', 'companyName', 'tax', 'month', 'year', 'amount', 'ufficio_Ced_PA', 'numeroREA_Ced_PA', 'capitaleSociale_Ced_PA', 'socioUnico_Ced_PA', 'statoLiquidazione_Ced_PA');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);

	// template paths below are based on the app main directory
	$x->Template = 'templates/vatRegister_templateTV.html';
	$x->SelectedTemplate = 'templates/vatRegister_templateTVS.html';
	$x->TemplateDV = 'templates/vatRegister_templateDV.html';
	$x->TemplateDVP = 'templates/vatRegister_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `vatRegister`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='vatRegister' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `vatRegister`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='vatRegister' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`vatRegister`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: vatRegister_init
	$render=TRUE;
	if(function_exists('vatRegister_init')){
		$args=array();
		$render=vatRegister_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// column sums
	if(strpos($x->HTML, '<!-- tv data below -->')){
		// if printing multi-selection TV, calculate the sum only for the selected records
		if(isset($_REQUEST['Print_x']) && is_array($_REQUEST['record_selector'])){
			$QueryWhere = '';
			foreach($_REQUEST['record_selector'] as $id){   // get selected records
				if($id != '') $QueryWhere .= "'" . makeSafe($id) . "',";
			}
			if($QueryWhere != ''){
				$QueryWhere = 'where `vatRegister`.`id` in ('.substr($QueryWhere, 0, -1).')';
			}else{ // if no selected records, write the where clause to return an empty result
				$QueryWhere = 'where 1=0';
			}
		}else{
			$QueryWhere = $x->QueryWhere;
		}

		$sumQuery = "select sum(`vatRegister`.`amount`) from {$x->QueryFrom} {$QueryWhere}";
		$res = sql($sumQuery, $eo);
		if($row = db_fetch_row($res)){
			$sumRow = '<tr class="success">';
			if(!isset($_REQUEST['Print_x'])) $sumRow .= '<td class="text-center"><strong>&sum;</strong></td>';
			$sumRow .= '<td class="vatRegister-idCompany"></td>';
			$sumRow .= '<td class="vatRegister-companyName"></td>';
			$sumRow .= '<td class="vatRegister-tax"></td>';
			$sumRow .= '<td class="vatRegister-month"></td>';
			$sumRow .= '<td class="vatRegister-year"></td>';
			$sumRow .= "<td class=\"vatRegister-amount text-right\">{$row[0]}</td>";
			$sumRow .= '<td class="vatRegister-ufficio_Ced_PA"></td>';
			$sumRow .= '<td class="vatRegister-numeroREA_Ced_PA"></td>';
			$sumRow .= '<td class="vatRegister-capitaleSociale_Ced_PA"></td>';
			$sumRow .= '<td class="vatRegister-socioUnico_Ced_PA"></td>';
			$sumRow .= '<td class="vatRegister-statoLiquidazione_Ced_PA"></td>';
			$sumRow .= '</tr>';

			$x->HTML = str_replace('<!-- tv data below -->', '', $x->HTML);
			$x->HTML = str_replace('<!-- tv data above -->', $sumRow, $x->HTML);
		}
	}

	// hook: vatRegister_header
	$headerCode='';
	if(function_exists('vatRegister_header')){
		$args=array();
		$headerCode=vatRegister_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: vatRegister_footer
	$footerCode='';
	if(function_exists('vatRegister_footer')){
		$args=array();
		$footerCode=vatRegister_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>